### ISSUE TITLE
Uncaught TypeError: values.forEach is not a function

### ISSUE THREAD

**Issue by mumuJAVA** [ElemeFE/element-helper#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [element-helper](https://github.com/ElemeFE/element-helper) package 0.4.1

### Stack Trace

Uncaught TypeError: values.forEach is not a function

```
At C:\Users\mumu\.atom\packages\element-helper\lib\provider.js:183

TypeError: values.forEach is not a function
    at Object.getAttrValueSuggestion (/packages/element-helper/lib/provider.js:183:12)
    at Object.getSuggestions (/packages/element-helper/lib/provider.js:19:19)
    at providers.forEach.provider (D:/tool/Atom x64/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:286:58)
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (D:/tool/Atom x64/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:262:21)
    at AutocompleteManager.findSuggestions (D:/tool/Atom x64/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:254:23)
```

### Commands

```
  2x -1:52.7.0 core:move-left (input.hidden-input)
     -1:51.7.0 intentions:highlight (input.hidden-input)
     -1:51.6.0 core:save (input.hidden-input)
     -1:47 intentions:highlight (input.hidden-input)
     -1:46.9.0 core:save (input.hidden-input)
     -1:18.2.0 intentions:highlight (input.hidden-input)
 31x -1:18.1.0 core:undo (input.hidden-input)
     -0:58.5.0 intentions:highlight (input.hidden-input)
     -0:58.3.0 core:paste (input.hidden-input)
     -0:57.9.0 core:undo (input.hidden-input)
     -0:54.7.0 core:backspace (input.hidden-input)
     -0:52.3.0 intentions:highlight (input.hidden-input)
     -0:52.3.0 core:save (input.hidden-input)
     -0:37.1.0 intentions:highlight (input.hidden-input)
     -0:18.6.0 core:backspace (input.hidden-input)
     -0:15.4.0 autocomplete-plus:confirm (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
element-helper 0.4.1 
file-icons 2.1.13 
intentions 1.1.5 
language-vue 0.23.1 
linter 2.0.0 
linter-eslint 8.3.2 
linter-ui-default 1.6.10 
vue-element-ui-snippets 0.7.0 
```

**Comment by ShowJoy** [comment]
Can you provide me more steps or detailed information?

**Comment by ShowJoy** [comment]
close for inactivity
